# Usa una imagen oficial de Node.js como base
FROM node:20-alpine

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos de dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código fuente
COPY . .

# Construye el proyecto 
RUN npm run build

# Expone el puerto 
EXPOSE 5000

# Comando para iniciar la app
CMD ["npm", "run"]
